version: '3'

services:
  database:
    image: postgres
    container_name: database_brain_agriculture
    restart: always
    ports:
        - 5433:5432
    environment:
      - POSTGRES_USER=brain
      - POSTGRES_PASSWORD=Brain@123
      - POSTGRES_DB=brain_agriculture
    volumes:
      - ./pg_data:/data/postgres
    networks:
      - db_brain_agriculture


networks:
  db_brain_agriculture:
    driver: bridge
    